#!/bin/sh

alias vi='nvim'
alias vim='nvim'

alias all='ls -al'
alias .2='cd ../..'
alias .3='cd ../../..'
alias .4='cd ../../../..'
alias .5='cd ../../../../..'
mcd () { mkdir -p "$1" && cd "$1"; }    # make new dir and cd into it

alias tf='terraform'
alias v="aws-vault exec --debug --duration=1h"
